### ISSUE TITLE
X Error of failed request:  BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by humbertodias** [suntorvic/nugem#1]
# Tested on Ubuntu 23.04

### How to reproduce the error

* Install the dependencies
```shell
sudo apt install -y libsdl2-dev libsdl2-image-dev freeglut3-dev libglew-dev libglm-dev cmake g++
```
* Run
```shell
cd `mktemp -d`
git clone https://github.com/humbertodias/sdl-nugem .
cmake .
make
./nugem
```
* Output
```
[ 34%] Building CXX object CMakeFiles/nugem.dir/src/sceneloader.cpp.o
[ 38%] Building CXX object CMakeFiles/nugem.dir/src/scenemenu.cpp.o
[ 42%] Linking CXX executable nugem
[100%] Built target nugem
$ ./nugem 
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x40059c
  Serial number of failed request:  262
  Current serial number in output stream:  262
```

@flmmkch 
Does this [issue](https://github.com/flmmkch/nugem/issues/1) occur in your environment?

**Comment by flmmkch** [comment]
Hi @humbertodias, thank you for the fixes you've made in the build!
I have not really touched this project for quite a few years (though I went a bit further and cleaner on [nugem-rs](https://github.com/flmmkch/nugem-rs) in Rust).
I just tried again using your branch and at first I got an error, but it wasn't the same as yours exactly. I had a segmentation fault in [GlSpriteCollectionBuilder::build()](https://github.com/flmmkch/nugem/blob/master/src/glsprite.cpp#L105).
My issue was due to [a hard-coded path](https://github.com/flmmkch/nugem/blob/master/src/scenemenu.cpp#L52). You have to put files for one ore more Mugen characters in a `chars/{characterName}` subfolder of the working directory for the `nugem` command. Once I launched in the right working directory, the window opened successfully and could display the characters' sprites, but it can't do much more than that.

**Comment by humbertodias** [comment]
> Hi @humbertodias, thank you for the fixes you've made in the build! I have not really touched this project for quite a few years (though I went a bit further and cleaner on [nugem-rs](https://github.com/flmmkch/nugem-rs) in Rust). I just tried again using your branch and at first I got an error, but it wasn't the same as yours exactly. I had a segmentation fault in [GlSpriteCollectionBuilder::build()](https://github.com/flmmkch/nugem/blob/master/src/glsprite.cpp#L105). My issue was due to [a hard-coded path](https://github.com/flmmkch/nugem/blob/master/src/scenemenu.cpp#L52). You have to put files for one ore more Mugen characters in a `chars/{characterName}` subfolder of the working directory for the `nugem` command. Once I launched in the right working directory, the window opened successfully and could display the characters' sprites, but it can't do much more than that.

Thanks. Adding a character at *chars/xpto* It works!
![image](https://github.com/flmmkch/nugem/assets/9255997/7e8bce18-81e5-429a-82b3-14910c391cf5)
There is only one tiny thing that i noticed on [Window::resizeToFullscreen](https://github.com/humbertodias/sdl-nugem/blob/master/src/window.cpp#L47) it takes some milliseconds to popup the window and grab the index. That was the problem cause for me.
I'm gonna figure out how to wait until the window popup avoiding this error on runtime. Here I've reach success only on debug mode

**Comment by humbertodias** [comment]
Problem solved! [here](https://github.com/flmmkch/nugem/pull/2/commits/24f8ff8b433b50b1089ca60a9247caae4c5bfb5a)
Instead of creating the window and later on make it fullscreen. I've created already as **SDL_WINDOW_FULLSCREEN_DESKTOP** and borderless
```cpp
Window::Window()
{
    m_sdlWindow = SDL_CreateWindow(m_title.c_str(),
                                   SDL_WINDOWPOS_CENTERED,
                                   SDL_WINDOWPOS_CENTERED,
                                   DEFAULT_WINDOW_WIDTH, DEFAULT_WINDOW_HEIGHT,
                                   SDL_WINDOW_ALLOW_HIGHDPI | SDL_WINDOW_OPENGL | SDL_WINDOW_FULLSCREEN_DESKTOP);
    //resizeToFullscreen();
}
```
